version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: paddy_user
      POSTGRES_PASSWORD: paddy_pass
      POSTGRES_DB: paddy_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
